from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    target = Path(path)
    text = target.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"anchor not found in {path}: {old[:120]!r}")
    target.write_text(text.replace(old, new, 1), encoding="utf-8")


path = "cyberwatch/organisation_sector_llm.py"
old = '''def _legacy_candidate_has_current_support(\n    context: OrganisationContext, candidate: LlmOrganisationCandidate,\n) -> bool:\n    """Ne migre une ancienne décision que si sa base existe encore."""\n    evidence_types = set(context.evidence_types)\n    if candidate.basis == "explicit_activity":\n        return bool(context.activity_descriptions) or bool(\n            evidence_types & {"source_activity", "official_subject_activity"}\n        )\n    if candidate.basis == "structured_metadata":\n        return "structured_source" in evidence_types\n    if candidate.basis == "naf_support":\n        return bool(context.activity_code or context.activity_label)\n    if candidate.basis == "multiple_signals":\n        return len(context.evidence_details) >= 2\n    return False\n'''
new = '''def _legacy_candidate_has_current_support(\n    context: OrganisationContext, candidate: LlmOrganisationCandidate,\n) -> bool:\n    """Ne migre une ancienne décision que si sa base sectorielle reste cohérente.\n\n    Un simple maintien du nombre de preuves est insuffisant : le prompt courant\n    peut légitimement s'abstenir lorsque deux preuves pointent vers des secteurs\n    différents. La migration exige donc que les preuves pertinentes encore\n    présentes soutiennent le secteur historique sans contradiction.\n    """\n    def sectors_for(*evidence_types: str) -> list[str]:\n        allowed = set(evidence_types)\n        return [\n            str(evidence.get("sector") or "").strip()\n            for evidence in context.evidence_details\n            if str(evidence.get("type") or "").strip() in allowed\n            and str(evidence.get("sector") or "").strip() in config.SECTORS\n            and str(evidence.get("sector") or "").strip() != config.SECTOR_UNKNOWN\n        ]\n\n    if candidate.basis == "explicit_activity":\n        sectors = sectors_for("source_activity", "official_subject_activity")\n        return bool(sectors) and candidate.sector in sectors and all(\n            sector == candidate.sector for sector in sectors\n        )\n    if candidate.basis == "structured_metadata":\n        sectors = sectors_for("structured_source")\n        return bool(sectors) and candidate.sector in sectors and all(\n            sector == candidate.sector for sector in sectors\n        )\n    if candidate.basis == "naf_support":\n        sectors = sectors_for(osec.EVIDENCE_NAF_PRECISE)\n        return bool(sectors) and candidate.sector in sectors and all(\n            sector == candidate.sector for sector in sectors\n        )\n    if candidate.basis == "multiple_signals":\n        sectors = sectors_for(*osec.AUDITED_EVIDENCE_TYPES)\n        supporting = [sector for sector in sectors if sector == candidate.sector]\n        return len(supporting) >= 2 and len(set(sectors)) == 1\n    return False\n'''
replace_once(path, old, new)

# Ajoute les tests unitaires du conflit de signaux.
test_path = Path("tests/test_organisation_sector_llm.py")
text = test_path.read_text(encoding="utf-8")
anchor = '''def test_legacy_services_cache_for_social_context_requires_fresh_decision(make_item):\n'''
if anchor not in text:
    raise SystemExit("test anchor missing")
insert = '''def test_legacy_multiple_signals_requires_consistent_sector_support():\n    conflicting = osl.OrganisationContext(\n        organisation_key="zero logement vacant",\n        organisation="Zéro Logement Vacant",\n        evidence_types=("source_activity",),\n        evidence_details=(\n            {"type": "source_activity", "sector": config.SECTOR_ADMIN, "text": "service public"},\n            {"type": "source_activity", "sector": config.SECTOR_TECH, "text": "service numérique de l'État"},\n        ),\n    )\n    candidate = osl.LlmOrganisationCandidate(\n        "zero logement vacant", config.SECTOR_ADMIN, 0.78, "multiple_signals", "historique",\n    )\n    assert not osl._legacy_candidate_has_current_support(conflicting, candidate)\n\n    aligned = osl.OrganisationContext(\n        organisation_key="ultra premium direct",\n        organisation="Ultra Premium Direct",\n        evidence_types=("source_activity",),\n        evidence_details=(\n            {"type": "source_activity", "sector": osec.SECTOR_AGRICULTURE, "text": "alimentation pour chiens et chats"},\n            {"type": "source_activity", "sector": osec.SECTOR_AGRICULTURE, "text": "spécialiste français de l'alimentation animale"},\n        ),\n    )\n    aligned_candidate = osl.LlmOrganisationCandidate(\n        "ultra premium direct", osec.SECTOR_AGRICULTURE, 0.92, "multiple_signals", "historique",\n    )\n    assert osl._legacy_candidate_has_current_support(aligned, aligned_candidate)\n\n\ndef test_legacy_explicit_activity_rejects_conflicting_sector_evidence():\n    context = osl.OrganisationContext(\n        organisation_key="example",\n        organisation="Example",\n        evidence_types=("source_activity",),\n        evidence_details=(\n            {"type": "source_activity", "sector": config.SECTOR_RETAIL, "text": "vente en ligne"},\n            {"type": "source_activity", "sector": config.SECTOR_TECH, "text": "plateforme logicielle"},\n        ),\n    )\n    candidate = osl.LlmOrganisationCandidate(\n        "example", config.SECTOR_RETAIL, 0.80, "explicit_activity", "historique",\n    )\n    assert not osl._legacy_candidate_has_current_support(context, candidate)\n\n\n'''
test_path.write_text(text.replace(anchor, insert + anchor, 1), encoding="utf-8")

method = Path("METHODOLOGY.md")
with method.open("a", encoding="utf-8") as handle:
    handle.write("\n\nUne migration de cache positive exige en outre une cohérence sectorielle des preuves actuelles. Pour `multiple_signals`, au moins deux preuves doivent soutenir le secteur historique et aucune preuve sectorielle auditée ne doit pointer vers un autre secteur. Pour `explicit_activity` et `structured_metadata`, les preuves pertinentes présentes ne doivent pas se contredire. Un cas tel que `service public` + `service numérique de l'État` reste donc abstentionnel tant qu'une autorité plus forte ne tranche pas.\n")

print("cache compatibility conflict gate applied")
